---
title: "Report"
author: "Johannes Brachem"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    number_sections: yes
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
    toc_depth: '2'
subtitle: PsyFaKo Open Science Survey
---

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
```

- [Data Wrangling](https://jobrachem.github.io/savage_survey/wrangling.html)
- [Analysis](https://jobrachem.github.io/savage_survey/analysis.html)


```{r}
results <- readRDS("data/results.rds")
```

```{r}
results$data$q01 %>% 
  summarise(mean_qprs = mean(n_qrps_per_proj, na.rm = T),
            sd_qrps = sd(n_qrps_per_proj),
            mean_orps = mean(n_orps_per_proj, na.rm = T),
            sd_orps = sd(n_orps_per_proj))
```


```{r fig.width=9}
results$plots$plot02
```

```{r fig.width=9}
results$plots$plot03
```

```{r}
results$data$q04 %>% 
  mutate(share = round(share, 1)) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover")) %>% 
  scroll_box(height = "300px", width = "100%")
```

```{r fig.width=9}
results$plots$plot05
```


